name: CI

on:
  pull_request:
    branches: [v*, master]
    types: [opened, synchronize]
  push:
    branches: [v*, master]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: HUSKY=0 npm ci

      - name: Install kanban-cli dependencies
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: cd kanban-cli && HUSKY=0 npm install --ignore-scripts && cd ..
        shell: bash

      - name: Setup Husky
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: npx husky install

      - name: Lint
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: npm run lint

      - name: Build
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: npm run build

      - name: Run unit tests
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: npm run test:unit

      - name: Run integration tests
        if: steps.check-skip.outputs.SKIP_BUILD != 'true'
        run: npm run test:integration